services:
  postgres-db:
    image: "postgres:16.2-alpine3.19"
    environment:
      POSTGRES_DB: alarme-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5000:5432
